version: '3.8'

services:
  redis:
    image: 'redis'
    restart: always
    hostname: localhost
    container_name: redis
    ports:
    - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:latest'
    restart: always
    container_name: rabbitmq
    hostname: localhost
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"
